function [RptgenML_CReport1] = buildMLBP_algorithm
%BUILDMLBP_ALGORITHM
 
%  Auto-generated by MATLAB on 29-May-2017 10:50:34
 
% Create RptgenML.CReport
RptgenML_CReport1 = RptgenML.CReport('Description',...
'A report C:\Users\jugao\Documents\bloodpressureestimationml',...
'Format','dom-htmx',...
'PackageType','both',...
'Stylesheet','default-rg-html',...
'DirectoryType','pwd');
% setedit(RptgenML_CReport1);
 
% Create rptgen.cml_eval
rptgen_cml_eval1 = rptgen.cml_eval('isInsertString',false,'isDiary',false);
setParent(rptgen_cml_eval1,RptgenML_CReport1);
 
% Create rptgen.cfr_titlepage
rptgen_cfr_titlepage1 = rptgen.cfr_titlepage('DoSinglePage',true,...
'Copyright_Date','2017',...
'Copyright_Holder','GCS Technologies',...
'Include_Copyright',true,...
'Author','Jun Gao (GCS Technologies)',...
'Subtitle','MATLAB Version: 9.2.0.556344 (R2017a)',...
'Title','MLBP Algorithm');
rptgen_cfr_text1 = rptgen.cfr_text('Content',...
'This is the documentaltion of MLBP algorithms and frameworks.');
set(rptgen_cfr_titlepage1,'AbstractComp',rptgen_cfr_text1);
rptgen_cfr_text2 = rptgen.cfr_text('isBold',true,'isItalic',true,...
'Content',['Unless stated otherwise, GCS Technologies is the owner or ',newline,'the licensee of all intellectual property rights in MLBP Algorithm ',newline,'detailed in this document, including software, passwords, ',newline,'codes - used or supplied in connection with its operation - ',newline,'and the material published on it.  These works are protected',newline,'by IP and copyright laws and treaties around the world.  ',newline,'All such rights are reserved.']);
set(rptgen_cfr_titlepage1,'LegalNoticeComp',rptgen_cfr_text2);
rptgen_cfr_image1 = rptgen.cfr_image('FileName','','MaxViewportSize',[7 9]);
set(rptgen_cfr_titlepage1,'ImageComp',rptgen_cfr_image1);
setParent(rptgen_cfr_titlepage1,RptgenML_CReport1);
 
% Create rptgen.cfr_section
rptgen_cfr_section1 = rptgen.cfr_section('StyleName','rgChapterTitle',...
'SectionTitle','Physionet Record Acquisition');
setParent(rptgen_cfr_section1,RptgenML_CReport1);
 
% Create rptgen.cfr_paragraph
rptgen_cfr_paragraph1 = rptgen.cfr_paragraph('ParaTitle',...
'Help for Mimic class');
rptgen_cfr_text3 = rptgen.cfr_text('Content','');
set(rptgen_cfr_paragraph1,'ParaTextComp',rptgen_cfr_text3);
setParent(rptgen_cfr_paragraph1,rptgen_cfr_section1);
 
% Create rptgen.cfr_text
rptgen_cfr_text4 = rptgen.cfr_text('Content',...
['This is a section that provide help imformation for the " mimic" class. ',newline,'The "mimic" class defines all the necesary properties and methods to ',newline,'access and acquire data from public databae Physionet (MIT) that has ',newline,'large quantity of health records.',newline,'',newline,'------- Begin -------']);
setParent(rptgen_cfr_text4,rptgen_cfr_paragraph1);
 
% Create rptgen.cfr_text
rptgen_cfr_text5 = rptgen.cfr_text('Content','%<help(''mimic'')>');
setParent(rptgen_cfr_text5,rptgen_cfr_paragraph1);
 
% Create rptgen.cfr_text
rptgen_cfr_text6 = rptgen.cfr_text('Content',...
['',newline,'',newline,'-- end of Matlab help file --']);
setParent(rptgen_cfr_text6,rptgen_cfr_paragraph1);
 
